const STATUS_SUCCESS_MESSAGE = "Success";
const STATUS_FAILURE_MESSAGE = "Failure";

const STATUS_SUCCESS_CODE = 200;
const STATUS_FAILURE_CODE = 500;
const STATUS_NOT_FOUND_CODE = 404;
const STATUS_UNAUTHORIZED_CODE = 401;

export default {
  STATUS_SUCCESS_MESSAGE,
  STATUS_FAILURE_MESSAGE,
  STATUS_SUCCESS_CODE,
  STATUS_FAILURE_CODE,
  STATUS_NOT_FOUND_CODE,
  STATUS_UNAUTHORIZED_CODE
};
